development:
  adapter: postgresql
  encoding: unicode
  database: stripstarter
  pool: 5
  username: stripstarter
  password: stripstarter

test:
  adapter: postgresql
  encoding: unicode
  database: stripstarter
  pool: 5
  username: stripstarter
  password: stripstarter